# Apptainer
- name: install apptainer
  apt:
    deb: https://github.com/apptainer/apptainer/releases/download/v1.5.3/apptainer_1.5.3-trixie+_amd64.deb 

- name: garante que existe o /opt/apptainer
  ansible.builtin.file:
    path: /opt/apptainer
    state: directory
    owner: root
    group: root
    mode: '755'

# Resto
- name: pacotes dev
  apt:
    update_cache: yes
    pkg:
      - amqp-tools
      - build-essential
      - curl
      - fish
      - gap
      - gdb
      - gfortran
      - git
      - jq
      - libfontconfig1-dev
      - libfribidi-dev
      - libgdal-dev
      - libgsl-dev
      - libharfbuzz-dev
      - libpnetcdf-dev
      - libnode-dev
      - libproj-dev
      - libudunits2-dev
      - libx11-dev
      - nasm
      - plink1.9
      - pnetcdf-bin
      - python3-pip
      - python3-pygments
      - texlive-full
      - octave
      - zbar-tools
      - zstd

