
- name: copia o script rstudio_tex.sh
  ansible.builtin.copy:
    src: rstudio_tex.sh
    dest: /usr/local/bin/rstudio_tex.sh
    owner: root
    group: root
    mode: '755'

- name: copia o instalador manual de texlive que instala em /opt/texlive
  ansible.builtin.copy:
    src: instala-opt-texlive.sh
    dest: /root/instala-opt-texlive.sh
    owner: root
    group: root
    mode: '700'

#Se eventualmente quisermos que rode o script de instalar texlive em /opt/texlive, descomentar abaixo
#instalação do zero: cerca de 90 minutos. Por enquanto preferimos executar manualmente.
#O mais rápido do zero: ssh root@brucutuvii.ime.usp.br "( cd /opt ; tar --zstd -cf - texlive;)" | tar --zstd -xf -
#O mais rápido para atualizar: rsync -a root@brucutuvii.ime.usp.br:/opt/texlive /opt/
#- name: instala ou atualiza TexLive completo em /opt/texlive para ser utilizado com imagens de R e Rstudio do Apptainer
#  ansible.builtin.script: instala-opt-texlive.sh
#  args:
#    executable: /root/instala-opt-texlive.sh

